{
 "title": "Monitoreo & Rastreo",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Monitoreo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitoreo Tiempo Real",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  last_update AS \"time\",\n  temperature AS \"Temperatura\",\n  humidity AS \"Humedad\"\nFROM Graficacion\nWHERE\n  $__timeFilter(last_update)\nORDER BY last_update"
    }
   ]
  },
  {
   "title": "Historico de Temperaturas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  last_update AS \"time\",\n  container_id AS metric,\n  temperature AS \"Temperatura\",\n  humidity AS \"Humedad\"\nFROM Graficacion\nWHERE\n  $__timeFilter(last_update)\nORDER BY last_update"
    }
   ]
  },
  { "title": "Localizacion Contenedores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Censado Histórico",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  last_update AS \"time\",\n  temperature,\n  humidity\nFROM Graficacion\nWHERE\n  $__timeFilter(last_update)\nORDER BY last_update"
    }
   ]
  },
  {
   "title": "Geolocalización",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  last_update AS \"time\",\n  longitude AS \"Longitud\",\n  latitude AS \"Latitud\"\nFROM Graficacion\nWHERE\n  $__timeFilter(last_update)\nORDER BY last_update"
    }
   ]
  }
 ]
}